blog/urls.py
from django.conf.urls import url
from .views import (post_detail, PostList, PostCreate,
    PostUpdate, PostDelete, PostArchiveYear,
    PostArchiveMonth)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name = "blog_post_list"),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name = "blog_post_archive_year"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name = "blog_post_archive_month"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail,
        name = "blog_post_detail"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name = "blog_post_update"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name = "blog_post_delete"),
    url(r'^create/$',
        PostCreate.as_view(),
        name = "blog_post_create"),
]

suorganiser/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from organiser.urls import (
    tag as tag_urls,
    startup as startup_urls,
    newslink as newslink_urls)
from blog import urls as blog_urls
from .views import redirect_root
from contact import urls as contact_urls
from django.contrib.flatpages import urls as flatpages_urls
from user import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
from blog.feeds import AtomPostFeed, Rss2PostFeed
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view)
from .sitemaps import sitemaps as sitemaps_dict
from organiser.views import Test

admin.site.site_header = "Startup Organiser Admin"
admin.site.site_title = "Startup Organiser Site Admin"
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

sitenews = [
    url(r'^atom/$',
        AtomPostFeed(),
        name = "blog_atom_feed"),
    url(r'^rss/$',
        Rss2PostFeed(),
        name = "blog_rss_feed"),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample\.json$', Test.as_view(), name = "my_json"),
    url(r'^$', redirect_root),
    url(r'^blog/', include(blog_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^startup/', include(startup_urls)),
    url(r'^newslink/', include(newslink_urls)),
    url(r'^user/', include(user_urls, namespace = "dj-auth")),
    url(r'^sitenews/', include(sitenews)),
    url(r'^sitemap\.xml$',
        site_index_view,
        {
            'sitemaps': sitemaps_dict,
            'sitemap_url_name': 'sitemap-section',
        },
        name = 'sitemap'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_view,
        {'sitemaps': sitemaps_dict},
        name = 'sitemap-section'),
    # url(r'^', include(flatpages_urls)),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

organiser/models.py
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from urllib.parse import urlparse

class TagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(
            slug = slug)


class Tag(models.Model):
    name = models.CharField(
        max_length = 31,
        unique = True)
    slug = models.SlugField(
        max_length = 31,
        unique = True,
        help_text = "A label for URL config.")
    objects = TagManager()

    def natural_key(self):
        return (
            self.slug)

    def get_absolute_url(self):
        return reverse(
            'organiser_tag_detail',
            kwargs = {
                'slug': self.slug})

    def get_update_url(self):
        return reverse(
            'organiser_tag_update',
            kwargs = {
                'slug': self.slug})

    def get_delete_url(self):
        return reverse(
            "organiser_tag_delete",
            kwargs = {
                "slug": self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class StartupManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug = slug)


class Startup(models.Model):
    name = models.CharField(
        max_length = 31,
        db_index = True
    )
    slug = models.SlugField(
        max_length = 31,
        unique = True,
        help_text = "A label for URL config."
    )
    description = models.TextField()
    founded_date = models.DateField(verbose_name = "founded date")
    contact = models.EmailField()
    website = models.URLField(max_length = 255)
    tags = models.ManyToManyField(Tag, blank = True)
    objects = StartupManager()

    def natural_key(self):
        return self.slug

    def get_absolute_url(self):
        return reverse(
            'organiser_startup_detail',
            kwargs = {
                'slug': self.slug})

    def get_update_url(self):
        return reverse(
            'organiser_startup_update',
            kwargs = {
                'slug': self.slug})

    def get_delete_url(self):
        return reverse(
            "organiser_startup_delete",
            kwargs = {
                'slug': self.slug})

    def get_feed_atom_url(self):
        return reverse(
            'organiser_startup_atom_feed',
            kwargs = {'startup_slug': self.slug})

    def get_feed_rss_url(self):
        return reverse(
            'organiser_startup_rss_feed',
            kwargs = {'startup_slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'


class NewsLinkManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug = slug)


class NewsLink(models.Model):
    title = models.CharField(max_length = 63)
    slug = models.SlugField(max_length = 63)
    pub_date = models.DateField("date published")
    link = models.URLField(max_length = 255)
    startup = models.ForeignKey(Startup, on_delete = models.CASCADE)
    objects = NewsLinkManager()

    def natural_key(self):
        return self.slug
        
    def get_absolute_url(self):
        return self.startup.get_absolute_url() 

    def get_update_url(self):
        return reverse(
            "organiser_newslink_update",
            kwargs = {
                'pk': self.pk})

    def get_delete_url(self):
        return reverse(
            "organiser_newslink_delete",
            kwargs = {
                'pk': self.pk})

    def description(self):
        return (
            "Written on "
            "{0:%A, %B} {0.day}, {0:%Y}; "
            "hosted at {1}".format(
                self.pub_date,
                urlparse(self.link).netloc))

    def __str__(self):
        return "{} : {}".format(
            self.startup, self.title)

    class Meta:
        verbose_name = "news article"
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        unique_together = ('slug', 'startup')

organiser/forms.py
from django.db import models
from django import forms
from django.core.exceptions import ValidationError
from .models import Tag, Startup, NewsLink

class SlugCleanMixin:
    """Mixin class for slug cleaning method"""
    
    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == "create":
            raise ValidationError(
                "Slug may not be create.")
        return new_slug

class TagForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

    def clean_name(self):
        return self.cleaned_data['name'].lower()

class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = "__all__"

class StartupForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = "__all__"

organiser/views.py
from django.shortcuts import render, get_object_or_404,\
    render_to_response, redirect
from django.http import HttpResponse, Http404
from .models import Tag, Startup, NewsLink
from django.template import loader, RequestContext
from .forms import TagForm, StartupForm, NewsLinkForm
from django.views.generic import View
from .utils import (
    ObjectCreateMixin, ObjectUpdateMixin, ObjectDeleteMixin,
    DetailView)
from django.urls import reverse_lazy, reverse
from django.core.paginator import (
    EmptyPage, PageNotAnInteger, Paginator)
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from user.decorators import require_authenticated_permission


class Test(View):
    def get(self, request):
        return render(
            request,
            "organiser/sample.json",
            {})

def startup_detail(request, slug):
    startup = get_object_or_404(Startup, slug__iexact = slug)
    print(request.user.id)
    return render(
        request, 
        "organiser/startup_detail.html",
        {"startup": startup}
    )

class StartupDetail(DetailView):
    model = Startup

class StartupList(View):
    page_kwarg = "page"
    template_name = "organiser/startup_list.html"
    paginate_by = 5

    def get(self, request):
        startups = Startup.objects.all()
        paginator = Paginator(startups, self.paginate_by)
        page_number = request.GET.get(self.page_kwarg)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        if page.has_previous():
            previous_url = "?{pkw}={n}".format(
                pkw = self.page_kwarg, 
                n = page.previous_page_number())
        else:
            previous_url = None
        if page.has_next():
            next_url = "?{pkw}={n}".format(
                pkw = self.page_kwarg,
                n = page.next_page_number())
        else:
            next_url = None
        context = {
            "next_page_url": next_url,
            "previous_page_url": previous_url,
            "startup_list": page,
            "paginator": paginator,
        }
        return render(
            request,
            self.template_name,
            context
        )

@require_authenticated_permission('organiser.add_startup')
class StartupCreate(ObjectCreateMixin, View):
    form_class = StartupForm
    template_name = "organiser/startup_form.html"

@require_authenticated_permission('organiser.change_startup')
class StartupUpdate(ObjectUpdateMixin, View):
    form_class = StartupForm
    model = Startup
    template_name = "organiser/startup_form_update.html"

@require_authenticated_permission('organiser.delete_startup')
class StartupDelete(ObjectDeleteMixin, View):
    model = Startup
    success_url = reverse_lazy("organiser_startup_list")
    template_name = "organiser/startup_confirm_delete.html"

def tag_list(request):
    redirect_url = reverse(
        "organiser_tag_page",
        kwargs = {
            "page_number": 1
        }
    )
    return redirect(redirect_url)

def tag_page_list(request, page_number):
    paginate_by = 5
    tags = Tag.objects.all()
    paginator = Paginator(tags, paginate_by)
    try:
        page = paginator.page(page_number)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    if page.has_previous():
        previous_url = reverse(
            "organiser_tag_page",
            kwargs = {
                "page_number": page.previous_page_number()
            })
    else:
        previous_url = None
    if page.has_next():
        next_url = reverse(
            "organiser_tag_page",
            kwargs = {
                "page_number": page.next_page_number()
            })
    else:
        next_url = None
    context = {
        "is_paginated": page.has_other_pages(),
        "next_page_url": next_url,
        "previous_page_url": previous_url,
        "paginator": paginator,
        "tag_list": page,
    }
    return render(
        request,
        "organiser/tag_list.html",
        context
    )

class TagDetail(DetailView):
    context_object_name = "tag"
    model = Tag
    template_name = "organiser/tag_detail.html"

@login_required
@permission_required("organiser.add_tag", raise_exception=True)
def tag_create(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            new_form = form.save()
            return redirect(new_form)
    else:
        form = TagForm()
    return render(
        request,
        'organiser/tag_form.html',
        {'form': form})

@require_authenticated_permission("organiser.change_tag")
class TagUpdate(ObjectUpdateMixin, View):
    form_class = TagForm
    model = Tag
    template_name = "organiser/tag_form_update.html"

@require_authenticated_permission("organiser.delete_tag")
class TagDelete(ObjectDeleteMixin, View):
    model = Tag
    success_url = reverse_lazy("organiser_tag_list")
    template_name = "organiser/tag_confirm_delete.html"
        
@require_authenticated_permission("organiser.add_newslink")
class NewsLinkCreate(ObjectCreateMixin, View):
    form_class = NewsLinkForm
    template_name = "organiser/newslink_form.html"

@require_authenticated_permission("organiser.change_newslink")
class NewsLinkUpdate(View):
    form_class = NewsLinkForm
    template_name = "organiser/newslink_form_update.html"

    def get(self, request, pk):
        newslink = get_object_or_404(
            NewsLink,
            pk = pk)
        return render(
            request,
            self.template_name,
            {
                "form": self.form_class(instance = newslink),
                "newslink": newslink
            }
        )

    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink,
            pk = pk)
        bound_form = TagForm(request.POST, instance = newslink)
        if bound_form.is_valid():
            new_newslink = bound_form.save()
            return redirect(new_newslink)
        else:
            return render(
                request,
                self.template_name,
                {
                    "form": bound_form,
                    "newslink": newslink
                }
            )

require_authenticated_permission("organiser.delete_newslink")
class NewsLinkDelete(View):

    def get(self, request, pk):
        newslink = get_object_or_404(
            NewsLink,
            pk = pk)
        return render(
            request,
            "organiser/newslink_confirm_delete.html",
            {'newslink': newslink}
        )

    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, 
            pk = pk)
        startup = newslink.startup
        newslink.delete()

#R4v3n

organiser/templates/organiser/base_organiser.html
{% extends parent_template|default:"base.html" %}
{% load blog_latest %}

{% block content %}
    <div class = "row">
        <section class = "eight columns">
            {% block org_content %}
                This is default content!
            {% endblock %}
        </section>
        <section class = "desktop four columns">
            {% block create_button %}{% endblock %}
            {% get_latest_posts 5 as custom_post_list %}
            <section class = "latest_posts">
                <h4>Latest Posts</h4>
                <ul>
                    {% for latest_post in custom_post_list %}
                        <li><a href = "{{ latest_post.get_absolute_url }}">
                            {{ latest_post.title }}
                        </a></li>
                    {% endfor %}
                </ul>
            </section>
        </section>
    </div>

    <div class = "row">
        <div class = "twelve columns">
            {% block content_footer %}{% endblock %}
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/newslink_confirm_delete.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Delete Newslink
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{{ newslink.get_delete_url }}" method = "POST">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete 
                    newslink {{ newslink.title }}?
                </p>
                <a href = "{{ newslink.get_absolute_url }}">Cancel</a>
                <button type = "submit">Delete Newslink</button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/newslink_form.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Link News Article to Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{% url 'organiser_newslink_create' %}" method = "POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type = "submit">
                    Link Article
                </button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/newslink_form_update.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Update Newslink
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{{ newslink.get_update_url }}" method = "POST">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.errors }}
                    <p>
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            {{ field.help_text }}
                        {% endif %}
                    </p>
                {% endfor %}
                <button type = "submit">Update Newslink</button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/startup_confirm_delete.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Delete Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{{ startup.get_delete_url }}" method = "POST">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete 
                    startup {{ startup.name }}?
                </p>
                <a href = "{{ startup.get_absolute_url }}">Cancel</a>
                <button type = "submit">Delete Startup</button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/startup_detail.html
{% extends parent_template|default:"organiser/base_organiser.html" %}
{% load obfuscate_email %}
{% load partial_post_list %}

{% block title %}
    {{ block.super }} - {{ startup.name|title }}
{% endblock %}

{% block content %}
    <article>
        <div class = "row">
        <div class = "offset-by-two eight columns">
        <h2>{{ startup.name }}</h2>
        <ul class = "inline">
            {% if perms.organiser.change_startup %}
            <li>
                <a href = "{{ startup.get_update_url }}" class = "button">Edit Startup</a>
            </li>
            {% endif %}
            {% if perms.organiser.delete_startup %}
            <li>
                <a href = "{{ startup.get_delete_url }}" class = "button">Delete Startup</a>
            </li>
            {% endif %}
        </ul>
        <dl>
            <dt>Date Founded</dt>
                <dd>{{ startup.founded_date }}</dd>
            <dt>Website</dt>
                <dd>{{ startup.website|urlize }}</dd>
            <dt>Contact</dt>
                <dd>{{ startup.contact|obfuscate }}</dd>
            
            <dt>Tag{{ startup.tags.count|pluralize }}</dt>
                {% for tag in startup.tags.all %}
                    <dd>
                        <a href = "{{ tag.get_absolute_url }}">
                            {{ tag.name|title }}</a>
                    </dd>
                {% endfor %}

            <dt>Feeds</dt>
                <dd>
                    <a href = "{{ startup.get_feed_atom_url }}">
                        Atom 
                    </a>
                </dd>
                <dd>
                    <a href = "{{ startup.get_feed_rss_url }}">
                        RSS 
                    </a>
                </dd>
        </dl>

        {{ startup.description|linebreaks }}
        </div></div>

            {% if startup.newslink_set.all %}
                <div class = "row">
                    <section class = "meta offset-by-two one-third column">
                        <h3>Recent News</h3>
                        {% if perms.organiser.add_newslink %}
                        <p>
                            <a href = "{% url 'organiser_newslink_create' %}" class = "button">Add Article</a>
                        </p>
                        {% endif %}
                        <ul class = "inline">
                            {% for newslink in startup.newslink_set.all %}
                                <li>
                                    <a href = "{{ newslink.link }}">
                                        {{ newslink.title|title }}</a>
                                    {% if perms.organiser.change_newslink %}
                                    (<a href = "{{ newslink.get_update_url }}">Edit</a>)
                                    {% endif %}
                                    {% if perms.organiser.delete_newslink %}
                                    (<a href = "{{ newslink.get_delete_url }}">Delete</a>)
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </section>
                </div>
            {% endif %}

            {% format_post_list startup %}
    </article>
{% endblock %}

organiser/templates/organiser/startup_form.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Create Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{% url 'organiser_startup_create' %}" method = "POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type = "submit">
                    Create Startup
                </button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/startup_form_update.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Update Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{{ startup.get_update_url }}" method = "POST">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.errors }}
                    <p>
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            {{ field.help_text }}
                        {% endif %}
                    </p>
                {% endfor %}
                <button type = "submit">Update Startup</button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/startup_list.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Startups
{% endblock %}

{% block create_button %}
    {% if perms.organiser.add_startup %}
    <a href = "{% url 'organiser_startup_create' %}" class = "button button-primary">
        Create New Startup
    </a>
    {% endif %}
{% endblock %}

{% block org_content %}
    <h2>Startup List</h2>
    {% if perms.organiser.add_startup %}
    <div class = "mobile">
        <a href = "{% url 'organiser_startup_create' %}" class = "button button-primary">Create New Startup</a>
    </div>
    {% endif %}
    <ul>
        {% for startup in startup_list %}
            <li>
                <a href = "{{ startup.get_absolute_url }}">
                    {{ startup.name }}</a>
                {% if perms.organiser.change_startup %}
                (<a href = "{{ startup.get_update_url }}">Edit</a>)
                {% endif %}
                {% if perms.organiser.delete_startup %}
                (<a href = "{{ startup.get_delete_url }}">Delete</a>)
                {% endif %}
            </li>
        {% empty %}
            <li><em>No Startups Available.</em></li>
        {% endfor %}
        {% if startup_list.has_other_pages %}
            <ul class = "inline">
                {% if previous_page_url %}
                    <li><a href = "{{ previous_page_url }}" class = "button">
                        Previous
                    </a></li>
                {% endif %}
                <li>
                    Page {{ startup_list.number }}
                    of {{ paginator.num_pages }}
                </li>
                {% if next_page_url %}
                    <li><a href = "{{ next_page_url }}" class = "button">
                        next
                    </a></li>
                {% endif %}
            </ul>
        {% endif %}
    </ul>
{% endblock %}

organiser/templates/organiser/tag_confirm_delete.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{{ tag.get_delete_url }}" method = "POST">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete 
                    tag {{ tag.name }}?
                </p>
                <a href = "{{ tag.get_absolute_url }}">Cancel</a>
                <button type = "submit">Delete Tag</button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/tag_detail.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
    <h2>{{ tag.name|title }}</h2>
    <ul class = "inline">
        <li>
            <a href = "{{ tag.get_update_url }}" class = "button">Edit Tag</a>
        </li>
        <li>
            <a href = "{{ tag.get_delete_url }}" class = "button">Delete Tag</a>
        </li>
    </ul>
    {% if tag.startup_set.all %}
        <section>
            <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
            <p>
                Tag is associated with 
                {{ tag.startup_set.count }}
                startup{{ tag.startup_set.count|pluralize }}
            </p>
            <ul>
                {% for startup in tag.startup_set.all %}
                    <li>
                        <a href = "{{ startup.get_absolute_url }}">{{ startup.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    {% if tag.blog_posts.all %}
        <section>
            <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
            <ul>
                {% for post in tag.blog_posts.all %}
                    <li>
                        <a href = "{{ post.get_absolute_url }}">{{ post.title|title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p> 
    {% endif %}
{% endblock %}

organiser/templates/organiser/tag_form.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{% url 'organiser_tag_create' %}" method = "POST">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <ul class = "custom_error_list">
                        {% for error in form.non_field_errors %}
                            <li><em>{{ error }}</em></li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <p>
                    <label for = "id_name">Name:</label>
                    {% if form.name.value %}
                        <input id = "id_name" maxlength = "31" name = "name" type = "text" value = "{{ form.name.value }}" />
                    {% else %}
                        <input id = "id_name" maxlength = "31" name = "name" type = "text" />
                    {% endif %}
                </p>
                {% if form.name.errors %}
                    <ul class = "custom_error_list">
                        {% for error in form.name.errors %}
                            <li><em>{{ error }}</em></li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <p>
                    <label for = "id_slug">Slug:</label>
                    {% if form.slug.value %}
                        <input id = "id_slug" maxlength = "31" name = "slug" type = "text" value = "{{ form.slug.value }}" />
                    {% else %}
                        <input id = "id_slug" maxlength = "31" name = "slug" type = "text" />
                    {% endif %}
                    <span class = "helptext">
                        A Label for URL config
                    </span>
                </p>
                {% if form.slug.errors %}
                    <ul class = "custom_error_list">
                        {% for error in form.slug.errors %}
                            <li><em>{{ error }}</em></li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <button type = "submit">
                    Create Tag
                </button>
            </form>
        </div>
    </div>
{% endblock %}

organiser/templates/organiser/tag_form_update.html
{% extends parent_template|default:"organiser/base_organiser.html" %}

{% block title %}
    {{ block.super }} - Update Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action = "{{ tag.get_update_url }}" method = "POST">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.errors }}
                    <p>
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            {{ field.help_text }}
                        {% endif %}
                    </p>
                {% endfor %}
                <button type = "submit">Update Tag</button>
            </form>
        </div>
    </div>
{% endblock %}