blog/urls.py
from django.conf.urls import url
from .views import (post_detail, PostList, PostCreate,
    PostUpdate, PostDelete, PostArchiveYear,
    PostArchiveMonth)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name = "blog_post_list"),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name = "blog_post_archive_year"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name = "blog_post_archive_month"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail,
        name = "blog_post_detail"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name = "blog_post_update"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name = "blog_post_delete"),
    url(r'^create/$',
        PostCreate.as_view(),
        name = "blog_post_create"),
]

suorganiser/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from organiser.urls import (
    tag as tag_urls,
    startup as startup_urls,
    newslink as newslink_urls)
from blog import urls as blog_urls
from .views import redirect_root
from contact import urls as contact_urls
from django.contrib.flatpages import urls as flatpages_urls
from user import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
from blog.feeds import AtomPostFeed, Rss2PostFeed
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view)
from .sitemaps import sitemaps as sitemaps_dict
from organiser.views import Test

admin.site.site_header = "Startup Organiser Admin"
admin.site.site_title = "Startup Organiser Site Admin"
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

sitenews = [
    url(r'^atom/$',
        AtomPostFeed(),
        name = "blog_atom_feed"),
    url(r'^rss/$',
        Rss2PostFeed(),
        name = "blog_rss_feed"),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample\.json$', Test.as_view(), name = "my_json"),
    url(r'^$', redirect_root),
    url(r'^blog/', include(blog_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^startup/', include(startup_urls)),
    url(r'^newslink/', include(newslink_urls)),
    url(r'^user/', include(user_urls, namespace = "dj-auth")),
    url(r'^sitenews/', include(sitenews)),
    url(r'^sitemap\.xml$',
        site_index_view,
        {
            'sitemaps': sitemaps_dict,
            'sitemap_url_name': 'sitemap-section',
        },
        name = 'sitemap'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_view,
        {'sitemaps': sitemaps_dict},
        name = 'sitemap-section'),
    # url(r'^', include(flatpages_urls)),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from .views import DisableAccount
from django.views.generic import RedirectView, TemplateView
from .views import (
    ActivateAccount, CreateAccount, DisableAccount, 
    ResendActivationEmail, ProfileDetail, ProfileUpdate,
    PublicProfileDetail)


app_name = "user"


password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name = 'dj-auth:pw_reset_start',
            permanent = False)),
    url(r'^change/$', 
        auth_views.PasswordChangeView.as_view(
            template_name = "user/password_change_form.html",
            success_url = reverse_lazy("dj-auth:pw_change_done")),
        name = "pw_change"),
    url(r'^change/done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name = "user/password_change_done.html"),
        name = "pw_change_done"),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name = "user/password_reset_form.html",
            email_template_name = "user/password_reset_email.txt",
            subject_template_name = "user/password_reset_subject.txt",
            success_url = reverse_lazy("dj-auth:pw_reset_sent")),
        name = "pw_reset_start"),
    url(r'^reset/sent/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name = "user/password_reset_sent.html"),
        name = "pw_reset_sent"),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = "user/password_reset_confirm.html",
            success_url = reverse_lazy('dj-auth:pw_reset_complete')),
        name = "pw_reset_confirm"),
    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name = "pw_reset_complete"),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name = "dj-auth:login",
            permanent = False)),
    url(r'^login/$', 
        auth_views.LoginView.as_view(
            template_name = "user/login.html",
            extra_context = {
                "form_class": AuthenticationForm}),
        name = "login"),
    url(r'^logout/$',
        auth_views.LogoutView.as_view(
            template_name = "user/logged_out.html",
            extra_context = {
                "form_class": AuthenticationForm}),
        name = "logout"),
    url(r'^password/', include(password_urls)),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name = 'disable'),
    url(r'^create/$',
        CreateAccount.as_view(),
        name = "create"),
    url(r'^create/done',
        TemplateView.as_view(
            template_name = ("user/user_create_done.html")),
        name = "create_done"),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name = "activate"),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name = "resend_activation"),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name = 'dj-auth:resend_activation',
            permanent = False)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name = 'profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name = 'profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name = 'public_profile'),
]

user/forms.py
import logging

from django import forms

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm as BaseUserCreationForm,
    UserChangeForm as BaseUserChangeForm)
from .utils import ActivationMailFormMixin
from django.core.exceptions import ValidationError 
from django.utils.text import slugify
from .models import Profile
from django.contrib.messages import error


logger = logging.getLogger(__name__)

class ResendActivationEmailForm(ActivationMailFormMixin, forms.Form):
    
    email = forms.EmailField()

    mail_validation_error = (
        'could not re-send activation email. '
        'Please try again later. (Sorry!)')

    def save(self, **kwargs):
        User = get_user_model()
        try:
            user = User.objects.get(email = self.cleaned_data['email'])
        except:
            logger.warning(
                'Resend Activation: No user with '
                'email: {} .'.format(
                    self.cleaned_data['email']))
            return None
        self.send_mail(user = user, **kwargs)
        return user


class UserCreationForm(ActivationMailFormMixin, BaseUserCreationForm):
    
    name = forms.CharField(
        max_length = 255,
        help_text = (
            "The name displayed on your "
            "public profile."))

    mail_validation_error = (
        "User created. Could not send activation "
        "email. Please try again later. (Sorry!)")

    class Meta(BaseUserCreationForm.Meta):
        model = get_user_model()
        fields = ("name", "email")
    
    def clean_name(self):
        name = self.cleaned_data['name']
        disallowed = (
            'activate',
            'create',
            'disable',
            'login',
            'logout',
            'password',
            'profile',
        )
        try:
            Profile.objects.get(name=name)
            raise_error = True
        except Profile.DoesNotExist:
            raise_error = False
        if name in disallowed or raise_error:
            raise ValidationError(
                "A user with that name"
                " already exists.")
        return name

    def save(self, **kwargs):
        user = super().save(commit = False)
        # if not user.pk:
        #     user.is_active = False
        #     send_mail = True
        # else:
        #     send_mail = False
        user.save()
        self.save_m2m()
        Profile.objects.update_or_create(
            user = user,
            defaults = {
                'name': self.cleaned_data['name'],
                'slug': slugify(
                    self.cleaned_data['name']),
            })
        # if send_mail:
        #     print(kwargs)
        #     me = self.send_mail(user = user, **kwargs)
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["about", "profile_image"]

class UserChangeForm(BaseUserChangeForm):
    """For UserAdmin."""

    class Meta(BaseUserChangeForm.Meta):
        model = get_user_model()

user/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth import get_user, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from django.urls import reverse_lazy
from .utils import MailContextViewMixin, ProfileGetObjectMixin
from .forms import UserCreationForm, ResendActivationEmailForm, ProfileForm
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.messages import success, error
from django.views.decorators.cache import never_cache
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator as token_generator
from .models import Profile
from .decorators import class_login_required
from django.shortcuts import get_object_or_404


class DisableAccount(View):
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = ('user/user_confirm_delete.html')

    @method_decorator(login_required)
    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request, 
            self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self, request):
        user = get_user(request)
        user.set_unusable_password()
        user.is_active = False
        user.save()
        logout(request)
        return redirect(self.success_url)

class CreateAccount(MailContextViewMixin, View):
    form_class = UserCreationForm
    success_url = reverse_lazy("dj-auth:login")
    template_name = "user/user_create.html"
    
    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form': self.form_class()}
        )
    
    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save(**self.get_save_kwargs(request))
            # if bound_form.mail_sent:
            success(request, "Account created successfully, you may now log in")
            return redirect(self.success_url)
            # else:
            #     errs = bound_form.non_field_errors()
            #     for err in errs:
            #         error(request, err)
            #     return redirect('dj-auth:resend_activation')
        return TemplateResponse(
            request, 
            self.template_name,
            {'form': bound_form}
        )

class ActivateAccount(View):
    success_url = reverse_lazy("dj-auth:login")
    template_name = "user/user_activate.html"

    @method_decorator(never_cache)
    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk = uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if (user is not None and token_generator.check_token(user, token)):
            user.is_active = True
            user.save()
            success(
                request,
                'User Activated! '
                'You may now login.')
            return redirect(self.success_url)
        else:
            return TemplateResponse(
                request,
                self.template_name
            )

class ResendActivationEmail(MailContextViewMixin, View):
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy("dj-auth:login")
    template_name = "user/resend_activation.html"

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form': self.form_class()}
        )

    @method_decorator(csrf_protect)
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            user = bound_form.save(**self.get_save_kwargs(request))
            if (user is not None and not bound_form.mail_sent):
                errs = (bound_form.non_field_errors())
                for err in errs:
                    error(request, err)
                if errs:
                    bound_form.errors.pop("__all__")
                return TemplateResponse(
                    request,
                    self.template_name,
                    {'form': bound_form})
        success(
            request,
            'Activation Email Sent!')
        return redirect(self.success_url)


@class_login_required
class ProfileDetail(ProfileGetObjectMixin, View):
    template_name = "user/profile_detail.html"

    def get(self, request):
        profile = self.get_object(request)
        return render(
            request,
            self.template_name,
            {'profile': profile}
        )


@class_login_required
class ProfileUpdate(ProfileGetObjectMixin, View):
    form_class = ProfileForm
    model = Profile
    template_name = "user/profile_form_update.html"
    success_url = reverse_lazy("dj-auth:profile")

    def get(self, request):
        profile = get_object_or_404(
            Profile,
            user = get_user(request))
        context = {
            'form': self.form_class(instance = profile),
            'profile': profile}
        return render(
            request,
            self.template_name,
            context
        )

    def post(self, request):
        profile = get_object_or_404(
            Profile,
            user = get_user(request))
        bound_form = self.form_class(request.POST, request.FILES, instance = profile)
        if bound_form.is_valid():
            bound_form.save()
            return redirect(self.success_url)
        else:
            context = {
            'form': bound_form,
            'profile': profile}
            return render(
                request,
                self.template_name,
                context
            )


class PublicProfileDetail(View):

    def get(self, request, slug):
        profile = get_object_or_404(
            Profile,
            slug__iexact = slug)
        return render(
            request,
            "user/profile_detail.html",
            {'profile': profile},
        )

user/templates/user/base_user.html
{% extends parent_template|default:"base.html" %}

user/templates/user/logged_out.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Logged Out
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <p>You've successfully logged out.</p>
            {% include "user/login_form.html" with login_button="Log Back In" %}
        </div>
    </div>
{% endblock %}

user/templates/user/login.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Login
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two five columns">
            {% include "user/login_form.html" with login_button='Log In' %}
        </div>
    </div>
    <div class ="offset-by-two three columns">
        <ul class = "task-list">
            <!-- <li><a href = "{% url 'dj-auth:pw_reset_start' %}">
                Forgotten Password?
            </a></li>
            <li><a href = "{% url 'dj-auth:resend_activation' %}">
                Lost Activation E-Mail?
            </a></li> -->
            <li><a href = "{% url 'dj-auth:create' %}">
                Register New Account
            </a></li>
        </ul>
    </div>
{% endblock %}

user/templates/user/login_form.html
<form action = "{% url 'dj-auth:login' %}" method = "POST">
    {% csrf_token %}
    {{ form_class.as_p }}
    {{ form_class.errors }}
    <button type = "submit">{{ login_button|default:"Log In" }}</button>
    {% if next %}
        <input type = "hidden" name = "next"  value = "{{ next }}" />
    {% endif %}
</form>

user/templates/user/password_change_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Change Password
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <p>Password successfully changed.</p>
        </div>
    </div>
{% endblock %}

user/templates/user/password_change_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Change Password 
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <form action = "{% url 'dj-auth:pw_change' %}" method = "POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type = "submit">Change Password</button>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            {% if validlink %}
                <p>Enter a new password below.</p>
                <form action = "{{ request.path }}" method = "POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class = "button-primary" type = "submit">Save New Password</button>
                </form>
            {% else %}
                <P>This reset link is no longer valid.</P>
                <p>Please request a new reset email
                    <a href = "{% url 'dj-auth:pw_reset_start' %}">here</a>.
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}  "

user/templates/user/password_reset_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <div class = "center">
                <p>Reset your password by email.</p>
            </div>
            <form action = "{% url 'dj-auth:pw_reset_start' %}" method = "POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type = "submit">Send Me Reset Instructions.</button>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/password_reset_sent.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Password Reset Sent
{% endblock %}

{% block content %}
    <div class = 'row'>
        <div class = 'offset-by-two eight columns'>
            <p>Password reset email sent!</p>
            <p>Please check your inbox and spam box.</p>
        </div>
    </div>
{% endblock %}

user/templates/user/profile_detail.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - {{ profile.user.get_full_name }}'s Profile
{% endblock %}

{% block content %}
    <div class = "row">
        {% if user.pk == profile.user.pk %}
            <div class = "offset-by-two five columns">
        {% else %}
            <div class = "offset-by-two eight columns">
        {% endif %}
            <h2>{{ profile.user.get_full_name }}</h2>
            {% if profile.profile_image %}
                <p>
                    <a href = "{{ profile.profile_image.url }}">
                        <img class = 'profile_image' src = "{{ profile.profile_image.url }}" alt = "profile image">
                    </a>
                    </p>
            {% endif %}
            {{ profile.about|default:"No Profile"|linebreaks }}
            {% if profile.user.published_posts|length > 0 %}
            <section>
                <h3>Blog Post{{ profile.user.published_posts|pluralize }}</h3>
                <ul>
                    {% for post in profile.user.published_posts %}
                        <li><a href = "{{ post.get_absolute_url }}">
                            {{ post.title|title }}
                        </a></li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
            </div>
        {% if user.pk == profile.user.pk %}
            <div class = "three columns">
                <ul class = "task-list">
                    <li>
                        <a href = "{% url 'dj-auth:profile_update' %}">
                            Update Profile
                        </a>
                    </li>
                    <li>
                        <a href = "{% url 'dj-auth:pw_change' %}">
                            Change Password
                        </a>
                    </li>
                    <li>
                        <a href = "{% url 'dj-auth:disable' %}">
                            Disable Account
                        </a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock %}

user/templates/user/resend_activation.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Resend Activation E-mail
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <div class = "center">
                <p>Resend your account activation email.</p>
            </div>
            <form action = "{% url 'dj-auth:resend_activation' %}" method = "POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type = "submit">Resend Activation E-Mail</button>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/user_confirm_delete.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Disable Account
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <p>Disable your account?</p>
            <p>This cannot be undone.</p>
            <form action = "{% url 'dj-auth:disable' %}" method = "POST">
                {% csrf_token %}
                <button type = "submit">
                    Disable Account
                </button>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/user_create.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Create Account
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <!-- <div class = "center">
                <a href = "{% url 'dj-auth:resend_activation' %}">
                    Lost Activation E-Mail?
                </a>
            </div> -->
            <form action = "{% url 'dj-auth:create' %}" method = "POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type = "submit">Create New Account</button>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/user_create_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Account Created
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "offset-by-two eight columns">
            <p>Your account has been created!</p>
            <p>Please check your email for the activation link.</p>
        </div>
    </div>
{% endblock %}