blog/urls.py
from django.conf.urls import url
from .views import (post_detail, PostList, PostCreate,
    PostUpdate, PostDelete, PostArchiveYear,
    PostArchiveMonth)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name = "blog_post_list"),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name = "blog_post_archive_year"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name = "blog_post_archive_month"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail,
        name = "blog_post_detail"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name = "blog_post_update"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name = "blog_post_delete"),
    url(r'^create/$',
        PostCreate.as_view(),
        name = "blog_post_create"),
]

suorganiser/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from organiser.urls import (
    tag as tag_urls,
    startup as startup_urls,
    newslink as newslink_urls)
from blog import urls as blog_urls
from .views import redirect_root
from contact import urls as contact_urls
from django.contrib.flatpages import urls as flatpages_urls
from user import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
from blog.feeds import AtomPostFeed, Rss2PostFeed
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view)
from .sitemaps import sitemaps as sitemaps_dict
from organiser.views import Test

admin.site.site_header = "Startup Organiser Admin"
admin.site.site_title = "Startup Organiser Site Admin"
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

sitenews = [
    url(r'^atom/$',
        AtomPostFeed(),
        name = "blog_atom_feed"),
    url(r'^rss/$',
        Rss2PostFeed(),
        name = "blog_rss_feed"),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample\.json$', Test.as_view(), name = "my_json"),
    url(r'^$', redirect_root),
    url(r'^blog/', include(blog_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^startup/', include(startup_urls)),
    url(r'^newslink/', include(newslink_urls)),
    url(r'^user/', include(user_urls, namespace = "dj-auth")),
    url(r'^sitenews/', include(sitenews)),
    url(r'^sitemap\.xml$',
        site_index_view,
        {
            'sitemaps': sitemaps_dict,
            'sitemap_url_name': 'sitemap-section',
        },
        name = 'sitemap'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_view,
        {'sitemaps': sitemaps_dict},
        name = 'sitemap-section'),
    # url(r'^', include(flatpages_urls)),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from .views import DisableAccount
from django.views.generic import RedirectView, TemplateView
from .views import (
    ActivateAccount, CreateAccount, DisableAccount, 
    ResendActivationEmail, ProfileDetail, ProfileUpdate,
    PublicProfileDetail)


app_name = "user"


password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name = 'dj-auth:pw_reset_start',
            permanent = False)),
    url(r'^change/$', 
        auth_views.PasswordChangeView.as_view(
            template_name = "user/password_change_form.html",
            success_url = reverse_lazy("dj-auth:pw_change_done")),
        name = "pw_change"),
    url(r'^change/done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name = "user/password_change_done.html"),
        name = "pw_change_done"),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name = "user/password_reset_form.html",
            email_template_name = "user/password_reset_email.txt",
            subject_template_name = "user/password_reset_subject.txt",
            success_url = reverse_lazy("dj-auth:pw_reset_sent")),
        name = "pw_reset_start"),
    url(r'^reset/sent/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name = "user/password_reset_sent.html"),
        name = "pw_reset_sent"),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = "user/password_reset_confirm.html",
            success_url = reverse_lazy('dj-auth:pw_reset_complete')),
        name = "pw_reset_confirm"),
    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name = "pw_reset_complete"),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name = "dj-auth:login",
            permanent = False)),
    url(r'^login/$', 
        auth_views.LoginView.as_view(
            template_name = "user/login.html",
            extra_context = {
                "form_class": AuthenticationForm}),
        name = "login"),
    url(r'^logout/$',
        auth_views.LogoutView.as_view(
            template_name = "user/logged_out.html",
            extra_context = {
                "form_class": AuthenticationForm}),
        name = "logout"),
    url(r'^password/', include(password_urls)),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name = 'disable'),
    url(r'^create/$',
        CreateAccount.as_view(),
        name = "create"),
    url(r'^create/done',
        TemplateView.as_view(
            template_name = ("user/user_create_done.html")),
        name = "create_done"),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name = "activate"),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name = "resend_activation"),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name = 'dj-auth:resend_activation',
            permanent = False)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name = 'profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name = 'profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name = 'public_profile'),
]

templates/base.html
{% load flatpages %}
{% load staticfiles %}
{% get_flatpages as flatpages %}
<!DOCTYPE html>
<html lang = "en">
    
    <head>
        <meta charset = "utf-8" />
        <title>
            {% block title %}
                Startup Organiser
            {% endblock %}
        </title>
        <meta http-equiv = "X-UA-Compatible" content = "IE=edge, chrome=1">
        <meta name = "viewport" content = "width=device-width, initial-scale=1">
        <!--[if IE]><script
            src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
        </script><![endif]-->
        <link href = "{% static 'site/normalize.css' %}" type = "text/css" rel = "stylesheet" />
        <link href = "{% static 'site/skeleton.css' %}" type = "text/css" rel = "stylesheet" />
        <link href = "{% static 'site/style.css' %}" type = "text/css" rel = "stylesheet" />
        <link rel = "alternate" title = "Blog News RSS" 
            type = "application/rss+xml" 
            href = "{% url 'blog_rss_feed' %}">
        <link rel = "alternate" title = "Blog News Atom"
            type = "application/atom+xml"
            href = "{% url 'blog_atom_feed' %}">
        <script src = "{% static 'organiser/js/jquery-3.4.1.min.js' %}"></script>
        {% block head %}{% endblock %}
    </head>

    <body>

        <div class = "container">
            <header class = "row">
                <div class = "offset-by-one ten columns">
                    <a href = "{% url 'blog_post_list' %}">
                        <h1 class = "logo">Startup Organiser</h1>
                    </a>
                </div>
            </header>
            <nav>
                <ul>
                    <li>
                        <a href = "{% url 'blog_post_list' %}">
                            Blog</a></li>
                    <li>
                        <a href = "{% url 'organiser_startup_list' %}">
                            Startups</a></li>
                    <li>
                        <a href = "{% url 'organiser_tag_list' %}">
                            Tags</a></li>
                    <li>
                        <a href = "{% url 'contact' %}">
                            Contact</a></li>
                    {% for page in flatpages %}
                        <li>
                            <a href = "{{ page.get_absolute_url }}">
                                {{ page.title }}</a></li>
                    {% endfor %}
                    {% if user.is_authenticated %}
                        <li>
                            <a href = "{% url 'dj-auth:profile' %}">
                                View Profile
                            </a></li>
                        <li>
                            <a href = "{% url 'dj-auth:logout' %}">
                                Log Out({{ user.profile.name }})</a></li>
                    {% else %}
                        <li>
                            <a href = "{% url 'dj-auth:login' %}?next={{ request.path }}">
                                Log In</a></li>
                        <li>
                            <a href = "{% url 'dj-auth:create' %}">
                                Register</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% if messages %}
                <div class = "row">
                    <div class = "twelve columns">
                        <ul class = "messages">
                            {% for message in messages %}
                                {% if message.tags %}
                                    <li class = "{{ message.tags }}">
                                        {{ message }}
                                    </li>
                                {% else %}
                                    <li>
                                        {{ message }}
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
            <main>
                {% block content %}
                    This is the default content!
                {% endblock %}
            </main>
        </div>

        <footer>
            <p>
                &copy; 2019
                <a href = "https://klyqinn.com">
                    Ikenna Anosike</a>
            </p>
            <p>
                Created for 
                <a href = "https://c0d3junk13.com/">
                    Django Unleashed</a>
            </p>
            <ul>
                <li>
                    <a href = "{% url 'blog_rss_feed' %}" class = "feed">
                        Blog RSS Feed
                    </a>
                </li>
                <li>
                    <a href = "{% url 'blog_atom_feed' %}" class = "feed">
                        Blog Atom Feed
                    </a>
                </li>
                <li>
                    <a href = "{% url 'sitemap' %}">Sitemap</a>
                </li>
            </ul>
        </footer>

        <script type = "text/javascript">
            function eject() {
                var myEl = document.getElementById("djDebugToolbar");
                var myLink = document.getElementById("djHideToolBarButton");
                myLink.addEventListener("click", (event) => {
                    myEl.remove();
                    event.stopPropagation();
                    document.body.removeEventListener("click", eject);
                })
            }
            document.body.addEventListener("click", eject);
        </script>
    </body>

</html>